/*
 *  Generated by matc (5.3.43); Fri Jun  2 10:58:24 2017
 */

#include <MaTXRC.h>

extern Matrix mp_data, PtoMR;
int mp1_old, mp2_old;
int pport_in_adr, pport_out_adr, pport_con_adr;

void sensor_init()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	void pport_init();
	int pport_in();

	pport_init();

	(mp1_old = pport_in((signed int)1));

	(mp2_old = pport_in((signed int)2));

	MatSetName(MatAssign(PtoMR, MatCatColumns(2,
	MatRowVec(1,
		6.09856e-5),
	MatRowVec(1,
		1.570796327e-3))), "PtoMR");

	MatSetName(MatAssign(mp_data, MatCatColumns(2,
	MatRowVec(1,
		0.0),
	MatRowVec(1,
		(- PI)))), "mp_data");

	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}

Matrix sensor()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	int mp1, mp2, mpd1, mpd2;
	int pport_in();

	(mp1 = pport_in((signed int)1));

	(mp2 = pport_in((signed int)2));

	(mpd1 = (mp1 - mp1_old));

	(mpd2 = (mp2 - mp2_old));

	(mp1_old = mp1);

	(mp2_old = mp2);

	if ( (mpd1 < (- (signed int)128)) ) {
		(mpd1 = (mpd1 + (signed int)256));

	} else if ( (mpd1 > (signed int)128) ) {
		(mpd1 = (mpd1 - (signed int)256));

	}
	if ( (mpd2 < (- (signed int)128)) ) {
		(mpd2 = (mpd2 + (signed int)256));

	} else if ( (mpd2 > (signed int)128) ) {
		(mpd2 = (mpd2 - (signed int)256));

	}
	MatSetName(MatAssign(mp_data, MatAdd(mp_data, MatCatColumns(2,
	MatRowVec(1,
		(6.09856e-5 * (double)mpd1)),
	MatRowVec(1,
		(1.570796327e-3 * (double)mpd2))))), "mp_data");

	{
		CompFrees(comp_last);
		mxStringFrees(str_last);
		MatFrees(mat_last);
		PolyFrees(poly_last);
		RatFrees(rat_last);
		ListFrees(list_last);
		return (mp_data);
	}
}

void actuator_init()
{

	int err;
	void pport_init(), actuator_stop();

	pport_init();

	actuator_stop();

}

void actuator_stop()
{

	void pport_out();

	pport_out((signed int)00);

}

void actuator(data)
	double data;
{

	int uv;
	void pport_out();

	if ( (data >= 0.0) ) {
		(uv = (int)rint((5.464 * data)));

	} else {
		(uv = (int)rint((6.061 * data)));

	}
	if ( (uv > (signed int)127) ) {
		(uv = (signed int)127);

	} else if ( (uv < (- (signed int)128)) ) {
		(uv = (- (signed int)128));

	}
	pport_out(uv);

}

int pport_in(p)
	int p;
{

	int stbh, stbl, sdh, opeh, opel;
	int x, y, xl, xh, yl, yh;
	void pport_out_stat();
	int arp_wait(), pport_in_data();

	(stbh = (signed int)0x001);

	(stbl = (signed int)0x000);

	(opeh = (signed int)0x008);

	(opel = (signed int)0x000);

	if ( (p == (signed int)1) ) {
		pport_out_stat((((signed int)0x000 << (signed int)1) | stbh));

		arp_wait(opeh);

		pport_out_stat((((signed int)0x000 << (signed int)1) | stbl));

		arp_wait(opel);

		(xl = (pport_in_data() & (signed int)0x0f0));

		pport_out_stat((((signed int)0x001 << (signed int)1) | stbh));

		arp_wait(opeh);

		pport_out_stat((((signed int)0x001 << (signed int)1) | stbl));

		arp_wait(opel);

		(xh = (pport_in_data() & (signed int)0x0f0));

		(x = (xh + (xl >> (signed int)4)));

		{
			return (x);
		}
	} else {
		pport_out_stat((((signed int)0x002 << (signed int)1) | stbh));

		arp_wait(opeh);

		pport_out_stat((((signed int)0x002 << (signed int)1) | stbl));

		arp_wait(opel);

		(yl = (pport_in_data() & (signed int)0x0f0));

		pport_out_stat((((signed int)0x003 << (signed int)1) | stbh));

		arp_wait(opeh);

		pport_out_stat((((signed int)0x003 << (signed int)1) | stbl));

		arp_wait(opel);

		(yh = (pport_in_data() & (signed int)0x0f0));

		pport_out_stat((((signed int)0x000 << (signed int)1) | stbh));

		(y = (yh + (yl >> (signed int)4)));

		{
			return (y);
		}
	}
}

void pport_out_data(x)
	int x;
{


	outb((unsigned char)x, (unsigned short)pport_out_adr);
}

void pport_out_stat(x)
	int x;
{


	outb((unsigned char)((x & (signed int)0x00f) ^ (signed int)0x00b), (unsigned short)pport_con_adr);
}

int pport_in_data()
{


	{
		return ((((unsigned char)inb((unsigned short)(pport_in_adr)) & (signed int)0x0f8) ^ (signed int)0x080));
	}
}

void pport_out(d)
	int d;
{

	int zero;

	(zero = (signed int)0x080);

	outb((unsigned char)(d + zero), (unsigned short)pport_out_adr);
}

int arp_wait(s)
	int s;
{

	int i, opeh;
	void arp_cpu_wait();

	(opeh = (signed int)0x008);

	for ( (i = (signed int)50000); (i > (signed int)00);i--) {
		if ( (((unsigned char)inb((unsigned short)(pport_in_adr)) & opeh) == s) ) {
			break;

		}
		arp_cpu_wait((signed int)1);

		MatObjectTmpUndef();
	}
	if ( (i == (signed int)00) ) {
		{
			return ((- (signed int)1));
		}
	} else {
		{
			return ((signed int)00);
		}
	}
}

void arp_cpu_wait(count)
	int count;
{

	int i;
	double x;

	(x = 1.0);

	for ( (i = (signed int)00); (i < count);i++) {
		(x = ((x * (double)i) * 3.0));

	}
}
