/*
 *  Generated by matc (5.3.43); Wed Jun 28 13:41:35 2017
 */

#include <MaTXRC.h>

double ref;
int cmd, count;
double smtime, yc, kc;
Matrix u, y;
Matrix data;
Matrix Ahd, Bhd, Chd, Dhd, Jhd, F;
Matrix z;
Matrix mp_data, PtoMR;
#include <MaTXGVAL.h>

/* for _controlfp() */
#if MSVC || BCC || __DJGPP__ || WATCOM
#include <float.h>
#endif

static void matx_die(int signo);
static void MatxSetSignal(void);
static void MatxMain(void);
static void MatxExit(void);

#ifndef HAVE_NO_SIGFPE
#ifndef __DJGPP__
static void matx_fpecatch(int signo);

static void matx_fpecatch(int signo)
{
	rtStop();
	exit(-2);
}
#endif
#endif

static void matx_die(int signo)
{
#ifndef HAVE_NO_SIGINT
	signal(SIGINT, SIG_IGN);
#endif
#ifndef HAVE_NO_SIGTERM
	signal(SIGTERM, SIG_IGN);
#endif
#ifndef HAVE_NO_SIGQUIT
	signal(SIGQUIT, SIG_IGN);
#endif
#ifndef HAVE_NO_SIGHUP
	signal(SIGHUP, SIG_IGN);
#endif
	MatxExit();
	exit(signo != 0);
}

static void MatxSetSignal(void)
{
#ifndef HAVE_NO_SIGFPE
#ifdef __DJGPP__
	if ((signal_type)signal(SIGFPE, SIG_IGN) == SIG_ERR)
		fprintf(stderr, "Can't catch SIGFPE\n");
#else
	if ((signal_type)signal(SIGFPE, SIG_IGN) != SIG_IGN)
		if ((signal_type)signal(SIGFPE, (signal_type)matx_fpecatch) == SIG_ERR)
			fprintf(stderr, "Can't catch SIGFPE\n");
#endif
#endif
#ifndef HAVE_NO_SIGINT
	if ((signal_type)signal(SIGINT, SIG_IGN) != SIG_IGN)
		if ((signal_type)signal(SIGINT, (signal_type)matx_die) == SIG_ERR)
			fprintf(stderr, "Can't catch SIGINT\n");
#endif
#ifndef HAVE_NO_SIGTERM
	if ((signal_type)signal(SIGTERM, SIG_IGN) != SIG_IGN)
		if ((signal_type)signal(SIGTERM, (signal_type)matx_die) == SIG_ERR)
			fprintf(stderr, "Can't catch SIGTERM\n");
#endif
#ifndef HAVE_NO_SIGQUIT
	if ((signal_type)signal(SIGQUIT, SIG_IGN) != SIG_IGN)
		if ((signal_type)signal(SIGQUIT, (signal_type)matx_die) == SIG_ERR)
			fprintf(stderr, "Can't catch SIGQUIT\n");
#endif
#ifndef HAVE_NO_SIGHUP
	if ((signal_type)signal(SIGHUP, SIG_IGN) != SIG_IGN)
		if ((signal_type)signal(SIGHUP, (signal_type)matx_die) == SIG_ERR)
			fprintf(stderr, "Can't catch SIGHUP\n");
#endif
}

int main(int argc, char *argv[])
{
#ifdef __DJGPP__
	/* ignore numerical exception */
	_fpreset();
	_clear87();
	_control87(MCW_EM, MCW_EM);
#endif
#if MSVC || WATCOM
	/* ignore numerical exception */
	_fpreset();
	_clearfp();
	_controlfp(MCW_EM, MCW_EM);
#endif
#if BCC
	/* ignore numerical exception */
	_fpreset();
	_clearfp();
	_controlfp(MCW_EM | MCW_PC, MCW_EM | MCW_PC);
#endif

	EPS = pow(2.0, -52.0); /* Set machine epsilon */
	matx_version(5.0); /* Set default version */
	matx_withlog_flag = 0;

	CompInit();
	mxStringInit();
	MatInit();
	PolyInit();
	RatInit();
	ListInit();
	u=MAT_STC, y=MAT_STC;
	data=MAT_STC;
	Ahd=MAT_STC, Bhd=MAT_STC, Chd=MAT_STC, Dhd=MAT_STC, Jhd=MAT_STC, F=MAT_STC;
	z=MAT_STC;
	mp_data=MAT_STC, PtoMR=MAT_STC;

#define MATXMAIN
#include <MaTXGVAL.h>

	MatxSetSignal();
	MatxMain();
	MatxExit();
	return 0;
}

/*
 *	This is called from MatError(), PolyError(),
 *	RatError(), and ListError().
 */
void execerror_recovery(void)
{
	MatxExit();
	exit(-1);
}

static void MatxExit(void)
{
#ifndef MSDOS
#ifndef X68K
#ifndef BSD_ON_WINDOWS
#ifndef DOS4GW
	graph_mgplot_quit(0);
#endif
#endif
#endif
#endif
}

static void MatxMain(void)
{

	void para_init(), var_init();
	void on_task(), break_task(), off_task_loop();
	void machine_ready(), machine_stop(), data_save();

	para_init();

	var_init();

	machine_ready();

	rtSetClock(smtime);

	rtSetTask((void (*)(void))on_task);

	rtSetBreak((void (*)(void))break_task);

	rtOnceTry();
	rtStart();
	off_task_loop();

	rtStop();
	rtResetTask();
	machine_stop();

	data_save();

}

void para_init()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	/* print -> "file"  and  read <- "file" */
	FILE *matx_fp;


	if ((matx_fp = datafile_read_open(mxStringString(mxStringStringDef("para.mx"))))) {
		MatSetType(MatSetName(MatRead(Ahd, matx_fp, MATRIX_T), "Ahd"), MAT_VAR);
		MatSetType(MatSetName(MatRead(Bhd, matx_fp, MATRIX_T), "Bhd"), MAT_VAR);
		MatSetType(MatSetName(MatRead(Chd, matx_fp, MATRIX_T), "Chd"), MAT_VAR);
		MatSetType(MatSetName(MatRead(Dhd, matx_fp, MATRIX_T), "Dhd"), MAT_VAR);
		MatSetType(MatSetName(MatRead(Jhd, matx_fp, MATRIX_T), "Jhd"), MAT_VAR);
		MatSetType(MatSetName(MatRead(F, matx_fp, MATRIX_T), "F"), MAT_VAR);
		fclose(matx_fp);
	}

	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}

void var_init()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;


	(smtime = 0.005);

	(cmd = (signed int)00);

	(count = (signed int)00);

	MatSetName(MatAssign(data, MatZDef2((signed int)4, (signed int)5000)), "data");

	MatSetName(MatAssign(z, MatTrans(MatRowVec(2,
		(double)(signed int)00,
		(double)(signed int)00))), "z");

	(ref = 0.1);

	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}

void on_task()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	Matrix xh=MAT_DEF, xref=MAT_DEF;
	Matrix sensor();
	void actuator();

	MatSetName(MatAssign(y, sensor()), "y");

	MatSetName(MatAssign(xh, MatAdd(MatMul(Chd, z), MatMul(Dhd, y))), "xh");

	if ( (((((double)count * smtime)) - ((signed int)5)*fix_to_zero((((double)count * smtime))/((signed int)5))) == (signed int)00) ) {
		(ref = fabs((ref - 0.1)));

	}
	MatSetName(MatAssign(xref, MatTrans(MatRowVec(4,
		ref,
		(double)(signed int)00,
		(double)(signed int)00,
		(double)(signed int)00))), "xref");

	MatSetName(MatAssign(u, MatMul(F, MatSub(xref, xh))), "u");

	MatSetName(MatAssign(z, MatAdd(MatAdd(MatMul(Ahd, z), MatMul(Bhd, y)), MatMul(Jhd, u))), "z");

	if ( ((cmd == (signed int)1) && (rtIsRehearsal() == 0)) ) {
		actuator(MatGetVecValue(u, (signed int)1));

	}
	if ( ((cmd == (signed int)1) && (count < (signed int)5000)) ) {
		count++;

		MatSetSubMatrix2(data, (signed int)1, (signed int)1, int_sgn((signed int)1-(signed int)1), count, count, 1, u),
		u;

		MatSetSubMatrix2(data, (signed int)2, (signed int)3, int_sgn((signed int)3-(signed int)2), count, count, 1, y),
		y;

		MatSetValue(data, (signed int)4, count, ref),
		ref;

	}
	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}

void off_task_loop()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	int end_flag;

	(end_flag = (signed int)00);

	util_disp_move((signed int)6, (signed int)5);
	printf("'c': アクチュエータへ出力開始");
	fflush(stdout);
	util_disp_move((signed int)7, (signed int)5);
	printf("ESC: アクチュエータへ出力停止");
	fflush(stdout);
	do {
		util_disp_move((signed int)11, (signed int)5);
		printf("  台車位置 = %8.4f[m], 振子角度 = %8.4f[deg]", MatGetVecValue(y, (signed int)1), ((MatGetVecValue(y, (signed int)2) / PI) * (double)(signed int)180));
		fflush(stdout);
		util_disp_move((signed int)12, (signed int)5);
		printf("入力 = %10.4f[N]", MatGetVecValue(u, (signed int)1));
		fflush(stdout);
		util_disp_move((signed int)14, (signed int)5);
		printf("データ数 = %4d, 時間 = %7.3f [s]", count, ((double)count * smtime));
		fflush(stdout);
		if ( rtIsTimeOut() ) {
			util_disp_move((signed int)18, (signed int)5);
			if (strlen("\n時間切れ !\n")) { aFilePrintf("stderr", "\n時間切れ !\n"); }
			MatObjectTmpUndef(); break;

		}
		if ( kbhit() ) {
			switch ( one_getch() ) {
				case 27:
				(end_flag = (signed int)1);

				break;
				case 67:
				case 99:
				(cmd = (signed int)1);

				break;
				case 82:
				case 114:
				util_disp_move((signed int)16, (signed int)5);
				fprintf(stdout, mxStringString(mxStringStringDef("台車の目標値 [m] : ")));
				fflush(stdout);
				ref = RealEdit(ref, "ref");
				util_disp_move((signed int)16, (signed int)5);
				printf("                                              ");
				fflush(stdout);
				break;
				default:
				break;
			}
		}
		MatObjectTmpUndef();
	} while ( (end_flag == 0) ) ;
	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}

void break_task()
{

	void machine_stop();

	rtStop();
	rtResetTask();
	machine_stop();

}

void machine_ready()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	void sensor_init(), actuator_init();

	sensor_init();

	actuator_init();

	util_disp_move((signed int)5, (signed int)5);
	printf("台車の初期位置 : レールの中央");
	fflush(stdout);
	util_disp_move((signed int)6, (signed int)5);
	printf("振子の初期位置 : 真下");
	fflush(stdout);
	util_disp_move((signed int)9, (signed int)5);
	pause_sleep(mxStringString(mxStringStringDef("台車と振子を初期位置に移動し，リターンキーを入力して下さい。")), 0.0);
	util_disp_move((signed int)9, (signed int)5);
	printf("                                                            ");
	fflush(stdout);
	util_disp_move((signed int)9, (signed int)5);
	pause_sleep(mxStringString(mxStringStringDef("リターンキーを入力すると，制御が開始されます。")), 0.0);
	system("clear");
	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}

void machine_stop()
{

	void actuator_stop();

	actuator_stop();

}

void data_save()
{

	Complex comp_last = COMP_DEF;
	mxString str_last = STRING_DEF;
	Matrix mat_last = MAT_DEF;
	Polynomial poly_last = POLY_DEF;
	Rational rat_last = RAT_DEF;
	List list_last = LIST_DEF;

	mxString filename=STRING_DEF;
	Matrix TT=MAT_DEF;

	mxStringSetName(mxStringAssign(filename, mxStringStringDef("")), "filename");

	mxStringAssign(filename, mxStringEdit(filename));
	mxStringSetName(filename, "filename");
	if ( (count > (signed int)1) ) {
		MatSetName(MatAssign(TT, MatScale(MatSeries((double)(signed int)00, (double)(count - (signed int)1), real_sgn((count - (signed int)1)-(double)(double)(signed int)00)), smtime)), "TT");

		MatFileWrite(MatCatColumns(2,
	TT,
	MatGetSubMatrix2(data, 1, Rows(data), 1, (signed int)1, count, int_sgn(count-(signed int)1))), mxStringString(mxStringAdd(filename, mxStringStringDef(".mat"))));
	}
	ListFrees(list_last);
	RatFrees(rat_last);
	PolyFrees(poly_last);
	MatFrees(mat_last);
	mxStringFrees(str_last);
	CompFrees(comp_last);
}
